/**
 * API Car plate - API Plaque immatriculation
 * Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@auto-ways.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.api;

import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * API Car plate - API Plaque immatriculation
 *
 * <p>Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.
 *
 * API tests for CarInfoApi 
 */
public class CarInfoApiTest {


    private CarInfoApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://app.auto-ways.net/api", CarInfoApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    /**
     * Find car by plate  , country  (ES)
     *
     * Return vehicle data from license plate
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCarByPlateEsTest() {
        String token = null;
        String plaque = null;
        String outputLang = null;
        //api.getCarByPlateEs(token, plaque, outputLang);
        
        // TODO: test validations
        
        
    }
    /**
     * Find car by plate , country  (FR)
     *
     * Return vehicle data from license plate
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCarByPlateFrTest() {
        String token = null;
        String plaque = null;
        String outputLang = null;
        //api.getCarByPlateFr(token, plaque, outputLang);
        
        // TODO: test validations
        
        
    }
    /**
     * Find car by plate  , country  (IT)
     *
     * Return vehicle data from license plate
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCarByPlateItTest() {
        String token = null;
        String plaque = null;
        String outputLang = null;
        //api.getCarByPlateIt(token, plaque, outputLang);
        
        // TODO: test validations
        
        
    }
    /**
     * Find car by plate  , country  (PT)
     *
     * Return vehicle data from license plate
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCarByPlatePtTest() {
        String token = null;
        String plaque = null;
        String outputLang = null;
        //api.getCarByPlatePt(token, plaque, outputLang);
        
        // TODO: test validations
        
        
    }
    /**
     * Find car by VIN
     *
     * Return vehicle data from license plate
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCarByVINTest() {
        String token = null;
        String vin = null;
        String outputLang = null;
        //api.getCarByVIN(token, vin, outputLang);
        
        // TODO: test validations
        
        
    }
}
