/*
 * API Car plate - API Plaque immatriculation
 * Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@auto-ways.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CarInfoApi
 */
@Ignore
public class CarInfoApiTest {

    private final CarInfoApi api = new CarInfoApi();

    /**
     * Find car by plate  , country  (ES)
     *
     * Return vehicle data from license plate
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCarByPlateEsTest() throws Exception {
        String token = null;
        String plaque = null;
        String outputLang = null;
        api.getCarByPlateEs(token, plaque, outputLang);

        // TODO: test validations
    }
    /**
     * Find car by plate , country  (FR)
     *
     * Return vehicle data from license plate
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCarByPlateFrTest() throws Exception {
        String token = null;
        String plaque = null;
        String outputLang = null;
        api.getCarByPlateFr(token, plaque, outputLang);

        // TODO: test validations
    }
    /**
     * Find car by plate  , country  (IT)
     *
     * Return vehicle data from license plate
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCarByPlateItTest() throws Exception {
        String token = null;
        String plaque = null;
        String outputLang = null;
        api.getCarByPlateIt(token, plaque, outputLang);

        // TODO: test validations
    }
    /**
     * Find car by plate  , country  (PT)
     *
     * Return vehicle data from license plate
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCarByPlatePtTest() throws Exception {
        String token = null;
        String plaque = null;
        String outputLang = null;
        api.getCarByPlatePt(token, plaque, outputLang);

        // TODO: test validations
    }
    /**
     * Find car by VIN
     *
     * Return vehicle data from license plate
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCarByVINTest() throws Exception {
        String token = null;
        String vin = null;
        String outputLang = null;
        api.getCarByVIN(token, vin, outputLang);

        // TODO: test validations
    }
}
