# coding: utf-8

# flake8: noqa
"""
    API Car plate - API Plaque immatriculation

    Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: contact@auto-ways.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
