/*
 * API Car plate - API Plaque immatriculation
 * Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@auto-ways.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {CarInfoApi} from './api/CarInfoApi';

/**
* Web_Service_which_allows_you_to_query_the_official_database_in_real_time_by_simply_entering_a_license_plate_or_a_VIN__You_allow_your_ecosystem_to_identify_in_one_click_the_official_data_of_a_vehicle_among_the_80M_license_plates_in_France_Spain_Italy_and_Portugal_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ApiCarPlateApiPlaqueImmatriculation = require('index'); // See note below*.
* var xxxSvc = new ApiCarPlateApiPlaqueImmatriculation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ApiCarPlateApiPlaqueImmatriculation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ApiCarPlateApiPlaqueImmatriculation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ApiCarPlateApiPlaqueImmatriculation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0-oas3
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
    * The CarInfoApi service constructor.
    * @property {module:api/CarInfoApi}
    */
    CarInfoApi
};
