/* 
 * API Car plate - API Plaque immatriculation
 *
 * Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@auto-ways.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CarInfoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CarInfoApiTests
    {
        private CarInfoApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CarInfoApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CarInfoApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CarInfoApi
            //Assert.IsInstanceOfType(typeof(CarInfoApi), instance, "instance is a CarInfoApi");
        }

        /// <summary>
        /// Test GetCarByPlateEs
        /// </summary>
        [Test]
        public void GetCarByPlateEsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string plaque = null;
            //string outputLang = null;
            //instance.GetCarByPlateEs(token, plaque, outputLang);
            
        }
        /// <summary>
        /// Test GetCarByPlateFr
        /// </summary>
        [Test]
        public void GetCarByPlateFrTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string plaque = null;
            //string outputLang = null;
            //instance.GetCarByPlateFr(token, plaque, outputLang);
            
        }
        /// <summary>
        /// Test GetCarByPlateIt
        /// </summary>
        [Test]
        public void GetCarByPlateItTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string plaque = null;
            //string outputLang = null;
            //instance.GetCarByPlateIt(token, plaque, outputLang);
            
        }
        /// <summary>
        /// Test GetCarByPlatePt
        /// </summary>
        [Test]
        public void GetCarByPlatePtTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string plaque = null;
            //string outputLang = null;
            //instance.GetCarByPlatePt(token, plaque, outputLang);
            
        }
        /// <summary>
        /// Test GetCarByVIN
        /// </summary>
        [Test]
        public void GetCarByVINTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //string vin = null;
            //string outputLang = null;
            //instance.GetCarByVIN(token, vin, outputLang);
            
        }
    }

}
