<?php
/**
 * CarInfoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API Car plate - API Plaque immatriculation
 *
 * Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: contact@auto-ways.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * CarInfoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CarInfoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCarByPlateEs
     *
     * Find car by plate  , country  (ES).
     *
     */
    public function testGetCarByPlateEs()
    {
    }

    /**
     * Test case for getCarByPlateFr
     *
     * Find car by plate , country  (FR).
     *
     */
    public function testGetCarByPlateFr()
    {
    }

    /**
     * Test case for getCarByPlateIt
     *
     * Find car by plate  , country  (IT).
     *
     */
    public function testGetCarByPlateIt()
    {
    }

    /**
     * Test case for getCarByPlatePt
     *
     * Find car by plate  , country  (PT).
     *
     */
    public function testGetCarByPlatePt()
    {
    }

    /**
     * Test case for getCarByVIN
     *
     * Find car by VIN.
     *
     */
    public function testGetCarByVIN()
    {
    }
}
