# coding: utf-8

"""
    API Car plate - API Plaque immatriculation

    Web Service which allows you to query the official database in real time by simply entering a license plate or a VIN. You allow your ecosystem to identify in one click the official data of a vehicle among the 80M license plates in France, Spain, Italy and Portugal.  # noqa: E501

    OpenAPI spec version: 1.0.0-oas3
    Contact: contact@auto-ways.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.car_info_api import CarInfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCarInfoApi(unittest.TestCase):
    """CarInfoApi unit test stubs"""

    def setUp(self):
        self.api = CarInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_car_by_plate_es(self):
        """Test case for get_car_by_plate_es

        Find car by plate  , country  (ES)  # noqa: E501
        """
        pass

    def test_get_car_by_plate_fr(self):
        """Test case for get_car_by_plate_fr

        Find car by plate , country  (FR)  # noqa: E501
        """
        pass

    def test_get_car_by_plate_it(self):
        """Test case for get_car_by_plate_it

        Find car by plate  , country  (IT)  # noqa: E501
        """
        pass

    def test_get_car_by_plate_pt(self):
        """Test case for get_car_by_plate_pt

        Find car by plate  , country  (PT)  # noqa: E501
        """
        pass

    def test_get_car_by_vin(self):
        """Test case for get_car_by_vin

        Find car by VIN  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
